services:
  db:
    image: postgres:15-alpine
    container_name: flashcards_postgres_db
    restart: always
    ports:
      - "7800:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - app_network

  flashcards_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcards_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:3000"
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:${PG_PASSWORD}@db:5432/mydb?schema=public
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "
      npx prisma generate &&
      npx prisma db seed &&
      npx prisma migrate deploy &&
      npm run start:dev
      "
    networks:
      - app_network
volumes:
  pgdata:
networks:
  app_network: